<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="THIYAGAM4" ignored="0" name="Test on Rest API" tests="10" failures="9" timestamp="08 May 2017 09:11:01 GMT" time="4.39" errors="0">
  <testcase name="getAE" time="2.111" classname="com.org.iot.test.smoke.Smoke"/>
  <testcase name="createGroup" time="0.311" classname="com.org.iot.test.smoke.Smoke">
    <failure type="java.io.FileNotFoundException" message="testdata.xls (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: testdata.xls (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.org.iot.test.smoke.Rand.setRandomGroup(Rand.java:87)
	at com.org.iot.test.smoke.Smoke.createGroup(Smoke.java:149)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- createGroup -->
  <testcase name="createContainer" time="0.04" classname="com.org.iot.test.smoke.Smoke">
    <failure type="java.io.FileNotFoundException" message="testdata.xls (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: testdata.xls (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.org.iot.test.smoke.Rand.setRandomContainer(Rand.java:53)
	at com.org.iot.test.smoke.Smoke.createContainer(Smoke.java:213)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- createContainer -->
  <testcase name="createSubscriptionGroup" time="0.04" classname="com.org.iot.test.smoke.Smoke">
    <failure type="java.io.FileNotFoundException" message="testdata.xls (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: testdata.xls (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.org.iot.test.smoke.Rand.setRandomSubscription_GRP(Rand.java:119)
	at com.org.iot.test.smoke.Smoke.createSubscriptionGroup(Smoke.java:281)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- createSubscriptionGroup -->
  <testcase name="createSubscriptionAE" time="0.04" classname="com.org.iot.test.smoke.Smoke">
    <failure type="java.io.FileNotFoundException" message="testdata.xls (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: testdata.xls (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.org.iot.test.smoke.Rand.setRandomSubscription_AE(Rand.java:151)
	at com.org.iot.test.smoke.Smoke.createSubscriptionAE(Smoke.java:357)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- createSubscriptionAE -->
  <testcase name="createSubscriptionCNT" time="0.04" classname="com.org.iot.test.smoke.Smoke">
    <failure type="java.io.FileNotFoundException" message="testdata.xls (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: testdata.xls (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.org.iot.test.smoke.Rand.setRandomSubscription_CNT(Rand.java:183)
	at com.org.iot.test.smoke.Smoke.createSubscriptionCNT(Smoke.java:433)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- createSubscriptionCNT -->
  <testcase name="getContainerData" time="0.09" classname="com.org.iot.test.smoke.Smoke">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.org.iot.test.smoke.Smoke.getContainerData(Smoke.java:547)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- getContainerData -->
  <testcase name="updateAE" time="0.03" classname="com.org.iot.test.smoke.Smoke">
    <failure type="java.io.FileNotFoundException" message="testdata.xls (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: testdata.xls (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.org.iot.test.smoke.Rand.setRandomAE_UPDATE_DATA(Rand.java:215)
	at com.org.iot.test.smoke.Smoke.updateAE(Smoke.java:571)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- updateAE -->
  <testcase name="updateCNT" time="0.04" classname="com.org.iot.test.smoke.Smoke">
    <failure type="java.io.FileNotFoundException" message="testdata.xls (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: testdata.xls (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.org.iot.test.smoke.Rand.setRandomCNT_UPDATE_DATA(Rand.java:247)
	at com.org.iot.test.smoke.Smoke.updateCNT(Smoke.java:647)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- updateCNT -->
  <testcase name="createSubscriptionMetadata" time="0.03" classname="com.org.iot.test.smoke.Smoke">
    <failure type="java.io.FileNotFoundException" message="testdata.xls (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: testdata.xls (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.org.iot.test.smoke.Rand.setRandomSubscription_META(Rand.java:279)
	at com.org.iot.test.smoke.Smoke.createSubscriptionMetadata(Smoke.java:742)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- createSubscriptionMetadata -->
</testsuite> <!-- Test on Rest API -->
